### ISSUE TITLE
Assess IntelliWait's usefullness

### ISSUE THREAD

**Issue by PandaMagnus** [IntelliTect/IntelliTect#26]
Kevin or Adam found the library Polly. See if it makes sense to continue to work on and support IntelliWait, or if it makes sense to convert over to using Polly.

**Comment by adamskt** [comment]
Currently using Polly in a SOAP service wrapper in a client project, so I'd be happy to discuss.

**Comment by joshward** [comment]
I also have used Polly for multiple projects and find it an essential library in my tool kit.

**Comment by PandaMagnus** [comment]
I should be in the office tomorrow afternoon. Will either of  you (both of you?) be around then to chat? If it doesn't get us anything of Polly, I'd like to obsolete it sooner rather than later just because there has been a handful of downloads, and don't want to have people hook into something that's not expected to be maintained.

**Comment by Keboo** [comment]
@PandaMagnus yea I will be in.

**Comment by PandaMagnus** [comment]
Finally had the opportunity to use Polly. It's pretty much exactly where I wanted to take IntelliWait. :O I'm going to obsolete this and direct people to Polly.

**Comment by PandaMagnus** [comment]
@adamskt @joshward @Keboo I added in an obsolete tag. Can someone review to make sure the messaging makes sense, and then maybe merge it into master? Please and thank you? :)
